# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_maintenance1
# VK_KHR_maintenance2
# VK_KHR_maintenance3
# VK_KHR_maintenance4

import ../../tools
const
  # VK_KHR_maintenance1
  KhrMaintenance1SpecVersion* = 2
  KhrMaintenance1ExtensionName* = "VK_KHR_maintenance1"
  # VK_KHR_maintenance2
  KhrMaintenance2SpecVersion* = 1
  KhrMaintenance2ExtensionName* = "VK_KHR_maintenance2"
  # VK_KHR_maintenance3
  KhrMaintenance3SpecVersion* = 1
  KhrMaintenance3ExtensionName* = "VK_KHR_maintenance3"
  # VK_KHR_maintenance4
  KhrMaintenance4SpecVersion* = 2
  KhrMaintenance4ExtensionName* = "VK_KHR_maintenance4"
  ImageAspectNoneKhr* = 0


# VK_KHR_maintenance1
# ===================
template trimCommandPoolKHR* = trimCommandPool

# VK_KHR_maintenance3
# ===================
template getDescriptorSetLayoutSupportKHR* = getDescriptorSetLayoutSupport

# VK_KHR_maintenance4
# ===================
proc getDeviceBufferMemoryRequirementsKHR*(
      device: Device;
      pInfo: ptr DeviceBufferMemoryRequirementsKHR;
      pMemoryRequirements: ptr MemoryRequirements2;
    ): void {.cdecl, lazyload("vkGetDeviceBufferMemoryRequirementsKHR", DeviceLevel).}
proc getDeviceImageMemoryRequirementsKHR*(
      device: Device;
      pInfo: ptr DeviceImageMemoryRequirementsKHR;
      pMemoryRequirements: ptr MemoryRequirements2;
    ): void {.cdecl, lazyload("vkGetDeviceImageMemoryRequirementsKHR", DeviceLevel).}
proc getDeviceImageSparseMemoryRequirementsKHR*(
      device: Device;
      pInfo: ptr DeviceImageMemoryRequirementsKHR;
      pSparseMemoryRequirementCount: ptr uint32;
      pSparseMemoryRequirements {.length: pSparseMemoryRequirementCount.} = default(arrPtr[SparseImageMemoryRequirements2]);
    ): void {.cdecl, lazyload("vkGetDeviceImageSparseMemoryRequirementsKHR", DeviceLevel).}


proc loadAllVK_KHR_maintenance4*(instance: Instance) = instance.loadCommands:
  getDeviceBufferMemoryRequirementsKHR
  getDeviceImageMemoryRequirementsKHR
  getDeviceImageSparseMemoryRequirementsKHR
proc loadVK_KHR_maintenance4*(device: Device) = device.loadCommands:
  getDeviceBufferMemoryRequirementsKHR
  getDeviceImageMemoryRequirementsKHR
  getDeviceImageSparseMemoryRequirementsKHR