# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_buffer_marker

import ../tools
const
  # VK_AMD_buffer_marker
  AmdBufferMarkerSpecVersion* = 1
  AmdBufferMarkerExtensionName* = "VK_AMD_buffer_marker"


# VK_AMD_buffer_marker
# ====================
proc cmdWriteBufferMarkerAMD*(
      commandBuffer: CommandBuffer;
      pipelineStage = default(PipelineStageFlagBits);
      dstBuffer: Buffer;
      dstOffset: DeviceSize;
      marker: uint32;
    ): void {.lazyload("vkCmdWriteBufferMarkerAMD", DeviceLevel), cmdchain.}


proc loadAllVK_AMD_buffer_marker*(instance: Instance) = instance.loadCommands:
  cmdWriteBufferMarkerAMD
proc loadVK_AMD_buffer_marker*(device: Device) = device.loadCommands:
  cmdWriteBufferMarkerAMD