# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_fragment_mask

const
  # VK_AMD_shader_fragment_mask
  AmdShaderFragmentMaskSpecVersion* = 1
  AmdShaderFragmentMaskExtensionName* = "VK_AMD_shader_fragment_mask"

