# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_gpu_shader_half_float

const
  # VK_AMD_gpu_shader_half_float
  AmdGpuShaderHalfFloatSpecVersion* = 2
  AmdGpuShaderHalfFloatExtensionName* = "VK_AMD_gpu_shader_half_float"

