# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_mixed_attachment_samples

const
  # VK_AMD_mixed_attachment_samples
  AmdMixedAttachmentSamplesSpecVersion* = 1
  AmdMixedAttachmentSamplesExtensionName* = "VK_AMD_mixed_attachment_samples"

