# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_negative_viewport_height

const
  # VK_AMD_negative_viewport_height
  AmdNegativeViewportHeightSpecVersion* = 1
  AmdNegativeViewportHeightExtensionName* = "VK_AMD_negative_viewport_height"

