# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_explicit_vertex_parameter

const
  # VK_AMD_shader_explicit_vertex_parameter
  AmdShaderExplicitVertexParameterSpecVersion* = 1
  AmdShaderExplicitVertexParameterExtensionName* = "VK_AMD_shader_explicit_vertex_parameter"

