# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_core_properties

const
  # VK_AMD_shader_core_properties
  AmdShaderCorePropertiesSpecVersion* = 2
  AmdShaderCorePropertiesExtensionName* = "VK_AMD_shader_core_properties"

