# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_ballot

const
  # VK_AMD_shader_ballot
  AmdShaderBallotSpecVersion* = 1
  AmdShaderBallotExtensionName* = "VK_AMD_shader_ballot"

