# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_gpu_shader_int16

const
  # VK_AMD_gpu_shader_int16
  AmdGpuShaderInt16SpecVersion* = 2
  AmdGpuShaderInt16ExtensionName* = "VK_AMD_gpu_shader_int16"

