# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_trinary_minmax

const
  # VK_AMD_shader_trinary_minmax
  AmdShaderTrinaryMinmaxSpecVersion* = 1
  AmdShaderTrinaryMinmaxExtensionName* = "VK_AMD_shader_trinary_minmax"

