# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_image_load_store_lod

const
  # VK_AMD_shader_image_load_store_lod
  AmdShaderImageLoadStoreLodSpecVersion* = 1
  AmdShaderImageLoadStoreLodExtensionName* = "VK_AMD_shader_image_load_store_lod"

