# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_shader_core_properties2

const
  # VK_AMD_shader_core_properties2
  AmdShaderCoreProperties2SpecVersion* = 1
  AmdShaderCoreProperties2ExtensionName* = "VK_AMD_shader_core_properties2"

