# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_gcn_shader

const
  # VK_AMD_gcn_shader
  AmdGcnShaderSpecVersion* = 1
  AmdGcnShaderExtensionName* = "VK_AMD_gcn_shader"

