# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_AMD_pipeline_compiler_control

const
  # VK_AMD_pipeline_compiler_control
  AmdPipelineCompilerControlSpecVersion* = 1
  AmdPipelineCompilerControlExtensionName* = "VK_AMD_pipeline_compiler_control"

