# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_shader_subgroup_vote

const
  # VK_EXT_shader_subgroup_vote
  ExtShaderSubgroupVoteSpecVersion* = 1
  ExtShaderSubgroupVoteExtensionName* = "VK_EXT_shader_subgroup_vote"

