# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_video_decode_h264

const
  # VK_EXT_video_decode_h264
  ExtVideoDecodeH264SpecVersion* = 3
  ExtVideoDecodeH264ExtensionName* = "VK_EXT_video_decode_h264"

