# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_line_rasterization

import ../tools
const
  # VK_EXT_line_rasterization
  ExtLineRasterizationSpecVersion* = 1
  ExtLineRasterizationExtensionName* = "VK_EXT_line_rasterization"


# VK_EXT_line_rasterization
# =========================
proc cmdSetLineStippleEXT*(
      commandBuffer: CommandBuffer;
      lineStippleFactor: uint32;
      lineStipplePattern: uint16;
    ): void {.lazyload("vkCmdSetLineStippleEXT", DeviceLevel), cmdchain.}


proc loadAllVK_EXT_line_rasterization*(instance: Instance) = instance.loadCommands:
  cmdSetLineStippleEXT
proc loadVK_EXT_line_rasterization*(device: Device) = device.loadCommands:
  cmdSetLineStippleEXT