# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_sample_locations

import ../tools
const
  # VK_EXT_sample_locations
  ExtSampleLocationsSpecVersion* = 1
  ExtSampleLocationsExtensionName* = "VK_EXT_sample_locations"


# VK_EXT_sample_locations
# =======================
proc cmdSetSampleLocationsEXT*(
      commandBuffer: CommandBuffer;
      pSampleLocationsInfo: ptr SampleLocationsInfoEXT;
    ): void {.lazyload("vkCmdSetSampleLocationsEXT", DeviceLevel), cmdchain.}
proc getPhysicalDeviceMultisamplePropertiesEXT*(
      physicalDevice: PhysicalDevice;
      samples: SampleCountFlagBits;
      pMultisampleProperties: ptr MultisamplePropertiesEXT;
    ): void {.lazyload("vkGetPhysicalDeviceMultisamplePropertiesEXT", InstanceLevel).}


proc loadAllVK_EXT_sample_locations*(instance: Instance) = instance.loadCommands:
  cmdSetSampleLocationsEXT
  getPhysicalDeviceMultisamplePropertiesEXT
proc loadVK_EXT_sample_locations*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceMultisamplePropertiesEXT
proc loadVK_EXT_sample_locations*(device: Device) = device.loadCommands:
  cmdSetSampleLocationsEXT