# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_image_drm_format_modifier

import ../tools
const
  # VK_EXT_image_drm_format_modifier
  ExtImageDrmFormatModifierSpecVersion* = 2
  ExtImageDrmFormatModifierExtensionName* = "VK_EXT_image_drm_format_modifier"


# VK_EXT_image_drm_format_modifier
# ================================
proc getImageDrmFormatModifierPropertiesEXT*(
      device: Device;
      image: Image;
      pProperties: ptr ImageDrmFormatModifierPropertiesEXT;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory],
      lazyload("vkGetImageDrmFormatModifierPropertiesEXT", DeviceLevel).}


proc loadAllVK_EXT_image_drm_format_modifier*(instance: Instance) = instance.loadCommands:
  getImageDrmFormatModifierPropertiesEXT
proc loadVK_EXT_image_drm_format_modifier*(device: Device) = device.loadCommands:
  getImageDrmFormatModifierPropertiesEXT