# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_physical_device_drm

const
  # VK_EXT_physical_device_drm
  ExtPhysicalDeviceDrmSpecVersion* = 1
  ExtPhysicalDeviceDrmExtensionName* = "VK_EXT_physical_device_drm"

