# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_transform_feedback

import ../tools
const
  # VK_EXT_transform_feedback
  ExtTransformFeedbackSpecVersion* = 1
  ExtTransformFeedbackExtensionName* = "VK_EXT_transform_feedback"


# VK_EXT_transform_feedback
# =========================
proc cmdBindTransformFeedbackBuffersEXT*(
      commandBuffer: CommandBuffer;
      firstBinding: uint32;
      bindingCount: uint32;
      pBuffers {.length: bindingCount.}: arrPtr[Buffer];
      pOffsets {.length: bindingCount.}: arrPtr[DeviceSize];
      pSizes {.length: bindingCount.} = default(arrPtr[DeviceSize]);
    ): void {.cdecl, lazyload("vkCmdBindTransformFeedbackBuffersEXT", DeviceLevel).}
proc cmdBeginTransformFeedbackEXT*(
      commandBuffer: CommandBuffer;
      firstCounterBuffer: uint32;
      counterBufferCount = default(uint32);
      pCounterBuffers {.length: counterBufferCount.}: arrPtr[Buffer];
      pCounterBufferOffsets {.length: counterBufferCount.} = default(arrPtr[DeviceSize]);
    ): void {.cdecl, lazyload("vkCmdBeginTransformFeedbackEXT", DeviceLevel).}
proc cmdEndTransformFeedbackEXT*(
      commandBuffer: CommandBuffer;
      firstCounterBuffer: uint32;
      counterBufferCount = default(uint32);
      pCounterBuffers {.length: counterBufferCount.}: arrPtr[Buffer];
      pCounterBufferOffsets {.length: counterBufferCount.} = default(arrPtr[DeviceSize]);
    ): void {.cdecl, lazyload("vkCmdEndTransformFeedbackEXT", DeviceLevel).}
proc cmdBeginQueryIndexedEXT*(
      commandBuffer: CommandBuffer;
      queryPool: QueryPool;
      query: uint32;
      flags = default(QueryControlFlags);
      index: uint32;
    ): void {.cdecl, lazyload("vkCmdBeginQueryIndexedEXT", DeviceLevel).}
proc cmdEndQueryIndexedEXT*(
      commandBuffer: CommandBuffer;
      queryPool: QueryPool;
      query: uint32;
      index: uint32;
    ): void {.cdecl, lazyload("vkCmdEndQueryIndexedEXT", DeviceLevel).}
proc cmdDrawIndirectByteCountEXT*(
      commandBuffer: CommandBuffer;
      instanceCount: uint32;
      firstInstance: uint32;
      counterBuffer: Buffer;
      counterBufferOffset: DeviceSize;
      counterOffset: uint32;
      vertexStride: uint32;
    ): void {.cdecl, lazyload("vkCmdDrawIndirectByteCountEXT", DeviceLevel).}


proc loadAllVK_EXT_transform_feedback*(instance: Instance) = instance.loadCommands:
  cmdBindTransformFeedbackBuffersEXT
  cmdBeginTransformFeedbackEXT
  cmdEndTransformFeedbackEXT
  cmdBeginQueryIndexedEXT
  cmdEndQueryIndexedEXT
  cmdDrawIndirectByteCountEXT
proc loadVK_EXT_transform_feedback*(device: Device) = device.loadCommands:
  cmdBindTransformFeedbackBuffersEXT
  cmdBeginTransformFeedbackEXT
  cmdEndTransformFeedbackEXT
  cmdBeginQueryIndexedEXT
  cmdEndQueryIndexedEXT
  cmdDrawIndirectByteCountEXT