# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_video_encode_h264

const
  # VK_EXT_video_encode_h264
  ExtVideoEncodeH264SpecVersion* = 3
  ExtVideoEncodeH264ExtensionName* = "VK_EXT_video_encode_h264"

