# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_validation_cache

import ../tools
const
  # VK_EXT_validation_cache
  ExtValidationCacheSpecVersion* = 1
  ExtValidationCacheExtensionName* = "VK_EXT_validation_cache"


# VK_EXT_validation_cache
# =======================
proc createValidationCacheEXT*(
      device: Device;
      pCreateInfo: ptr ValidationCacheCreateInfoEXT;
      pAllocator = default(ptr AllocationCallbacks);
      pValidationCache: ptr ValidationCacheEXT;
    ): Result {.lazyload("vkCreateValidationCacheEXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory].}
proc destroyValidationCacheEXT*(
      device: Device;
      validationCache = default(ValidationCacheEXT);
      pAllocator = default(ptr AllocationCallbacks);
    ): void {.lazyload("vkDestroyValidationCacheEXT", DeviceLevel).}
proc mergeValidationCachesEXT*(
      device: Device;
      dstCache: ValidationCacheEXT;
      srcCacheCount: uint32;
      pSrcCaches {.length: srcCacheCount.}: arrPtr[ValidationCacheEXT];
    ): Result {.lazyload("vkMergeValidationCachesEXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}
proc getValidationCacheDataEXT*(
      device: Device;
      validationCache: ValidationCacheEXT;
      pDataSize: ptr uint;
      pData {.length: pDataSize.} = default(pointer);
    ): Result {.lazyload("vkGetValidationCacheDataEXT", DeviceLevel),
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}


proc loadAllVK_EXT_validation_cache*(instance: Instance) = instance.loadCommands:
  createValidationCacheEXT
  destroyValidationCacheEXT
  mergeValidationCachesEXT
  getValidationCacheDataEXT
proc loadVK_EXT_validation_cache*(device: Device) = device.loadCommands:
  createValidationCacheEXT
  destroyValidationCacheEXT
  mergeValidationCachesEXT
  getValidationCacheDataEXT