# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_buffer_device_address

const
  # VK_EXT_buffer_device_address
  ExtBufferDeviceAddressSpecVersion* = 2
  ExtBufferDeviceAddressExtensionName* = "VK_EXT_buffer_device_address"


# VK_EXT_buffer_device_address
# ============================
template getBufferDeviceAddressEXT* = getBufferDeviceAddress

