# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_video_encode_h265

const
  # VK_EXT_video_encode_h265
  ExtVideoEncodeH265SpecVersion* = 3
  ExtVideoEncodeH265ExtensionName* = "VK_EXT_video_encode_h265"

