# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_fragment_density_map

const
  # VK_EXT_fragment_density_map
  ExtFragmentDensityMapSpecVersion* = 2
  ExtFragmentDensityMapExtensionName* = "VK_EXT_fragment_density_map"

