# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_border_color_swizzle

const
  # VK_EXT_border_color_swizzle
  ExtBorderColorSwizzleSpecVersion* = 1
  ExtBorderColorSwizzleExtensionName* = "VK_EXT_border_color_swizzle"

