# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_headless_surface

import ../tools
const
  # VK_EXT_headless_surface
  ExtHeadlessSurfaceSpecVersion* = 1
  ExtHeadlessSurfaceExtensionName* = "VK_EXT_headless_surface"


# VK_EXT_headless_surface
# =======================
proc createHeadlessSurfaceEXT*(
      instance: Instance;
      pCreateInfo: ptr HeadlessSurfaceCreateInfoEXT;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.lazyload("vkCreateHeadlessSurfaceEXT", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}


proc loadAllVK_EXT_headless_surface*(instance: Instance) = instance.loadCommands:
  createHeadlessSurfaceEXT
proc loadVK_EXT_headless_surface*(instance: Instance) = instance.loadCommands:
  createHeadlessSurfaceEXT