# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_post_depth_coverage

const
  # VK_EXT_post_depth_coverage
  ExtPostDepthCoverageSpecVersion* = 1
  ExtPostDepthCoverageExtensionName* = "VK_EXT_post_depth_coverage"

