# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_full_screen_exclusive

import ../tools
const
  # VK_EXT_full_screen_exclusive
  ExtFullScreenExclusiveSpecVersion* = 4
  ExtFullScreenExclusiveExtensionName* = "VK_EXT_full_screen_exclusive"


# VK_EXT_full_screen_exclusive
# ============================
proc getPhysicalDeviceSurfacePresentModes2EXT*(
      physicalDevice: PhysicalDevice;
      pSurfaceInfo: ptr PhysicalDeviceSurfaceInfo2KHR;
      pPresentModeCount: ptr uint32;
      pPresentModes {.length: pPresentModeCount.} = default(arrPtr[PresentModeKHR]);
    ): Result {.lazyload("vkGetPhysicalDeviceSurfacePresentModes2EXT", InstanceLevel),
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorSurfaceLostKhr].}
proc acquireFullScreenExclusiveModeEXT*(
      device: Device;
      swapchain: SwapchainKHR;
    ): Result {.lazyload("vkAcquireFullScreenExclusiveModeEXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorInitializationFailed, Result.errorSurfaceLostKhr].}
proc releaseFullScreenExclusiveModeEXT*(
      device: Device;
      swapchain: SwapchainKHR;
    ): Result {.lazyload("vkReleaseFullScreenExclusiveModeEXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorSurfaceLostKhr].}
proc getDeviceGroupSurfacePresentModes2EXT*(
      device: Device;
      pSurfaceInfo: ptr PhysicalDeviceSurfaceInfo2KHR;
      pModes: ptr DeviceGroupPresentModeFlagsKHR;
    ): Result {.lazyload("vkGetDeviceGroupSurfacePresentModes2EXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorSurfaceLostKhr].}


proc loadAllVK_EXT_full_screen_exclusive*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceSurfacePresentModes2EXT
  acquireFullScreenExclusiveModeEXT
  releaseFullScreenExclusiveModeEXT
  getDeviceGroupSurfacePresentModes2EXT
  getDeviceGroupSurfacePresentModes2EXT
proc loadVK_EXT_full_screen_exclusive*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceSurfacePresentModes2EXT
proc loadVK_EXT_full_screen_exclusive*(device: Device) = device.loadCommands:
  acquireFullScreenExclusiveModeEXT
  releaseFullScreenExclusiveModeEXT
  getDeviceGroupSurfacePresentModes2EXT
  getDeviceGroupSurfacePresentModes2EXT