# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_sampler_filter_minmax

const
  # VK_EXT_sampler_filter_minmax
  ExtSamplerFilterMinmaxSpecVersion* = 2
  ExtSamplerFilterMinmaxExtensionName* = "VK_EXT_sampler_filter_minmax"

