# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_device_memory_report

const
  # VK_EXT_device_memory_report
  ExtDeviceMemoryReportSpecVersion* = 2
  ExtDeviceMemoryReportExtensionName* = "VK_EXT_device_memory_report"

