# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_transform_feedback

import ../tools
const
  # VK_EXT_transform_feedback
  ExtTransformFeedbackSpecVersion* = 1
  ExtTransformFeedbackExtensionName* = "VK_EXT_transform_feedback"


# VK_EXT_transform_feedback
# =========================
proc cmdBindTransformFeedbackBuffersEXT*(
      commandBuffer: CommandBuffer;
      firstBinding: uint32;
      bindingCount: uint32;
      pBuffers {.length: bindingCount.}: arrPtr[Buffer];
      pOffsets {.length: bindingCount.}: arrPtr[DeviceSize];
      pSizes {.length: bindingCount.} = default(arrPtr[DeviceSize]);
    ): void {.lazyload("vkCmdBindTransformFeedbackBuffersEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdBeginTransformFeedbackEXT*(
      commandBuffer: CommandBuffer;
      firstCounterBuffer: uint32;
      counterBufferCount = default(uint32);
      pCounterBuffers {.length: counterBufferCount.}: arrPtr[Buffer];
      pCounterBufferOffsets {.length: counterBufferCount.} = default(arrPtr[DeviceSize]);
    ): void {.lazyload("vkCmdBeginTransformFeedbackEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdEndTransformFeedbackEXT*(
      commandBuffer: CommandBuffer;
      firstCounterBuffer: uint32;
      counterBufferCount = default(uint32);
      pCounterBuffers {.length: counterBufferCount.}: arrPtr[Buffer];
      pCounterBufferOffsets {.length: counterBufferCount.} = default(arrPtr[DeviceSize]);
    ): void {.lazyload("vkCmdEndTransformFeedbackEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdBeginQueryIndexedEXT*(
      commandBuffer: CommandBuffer;
      queryPool: QueryPool;
      query: uint32;
      flags = default(QueryControlFlags);
      index: uint32;
    ): void {.lazyload("vkCmdBeginQueryIndexedEXT", DeviceLevel),
      queues: QueueFlags{graphics, compute}, cmdchain.}
proc cmdEndQueryIndexedEXT*(
      commandBuffer: CommandBuffer;
      queryPool: QueryPool;
      query: uint32;
      index: uint32;
    ): void {.lazyload("vkCmdEndQueryIndexedEXT", DeviceLevel),
      queues: QueueFlags{graphics, compute}, cmdchain.}
proc cmdDrawIndirectByteCountEXT*(
      commandBuffer: CommandBuffer;
      instanceCount: uint32;
      firstInstance: uint32;
      counterBuffer: Buffer;
      counterBufferOffset: DeviceSize;
      counterOffset: uint32;
      vertexStride: uint32;
    ): void {.lazyload("vkCmdDrawIndirectByteCountEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}


proc loadAllVK_EXT_transform_feedback*(instance: Instance) = instance.loadCommands:
  cmdBindTransformFeedbackBuffersEXT
  cmdBeginTransformFeedbackEXT
  cmdEndTransformFeedbackEXT
  cmdBeginQueryIndexedEXT
  cmdEndQueryIndexedEXT
  cmdDrawIndirectByteCountEXT
proc loadVK_EXT_transform_feedback*(device: Device) = device.loadCommands:
  cmdBindTransformFeedbackBuffersEXT
  cmdBeginTransformFeedbackEXT
  cmdEndTransformFeedbackEXT
  cmdBeginQueryIndexedEXT
  cmdEndQueryIndexedEXT
  cmdDrawIndirectByteCountEXT