# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_load_store_op_none

const
  # VK_EXT_load_store_op_none
  ExtLoadStoreOpNoneSpecVersion* = 1
  ExtLoadStoreOpNoneExtensionName* = "VK_EXT_load_store_op_none"

