# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_validation_features

const
  # VK_EXT_validation_features
  ExtValidationFeaturesSpecVersion* = 5
  ExtValidationFeaturesExtensionName* = "VK_EXT_validation_features"

