# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_shader_stencil_export

const
  # VK_EXT_shader_stencil_export
  ExtShaderStencilExportSpecVersion* = 1
  ExtShaderStencilExportExtensionName* = "VK_EXT_shader_stencil_export"

