# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_pageable_device_local_memory

import ../tools
const
  # VK_EXT_pageable_device_local_memory
  ExtPageableDeviceLocalMemorySpecVersion* = 1
  ExtPageableDeviceLocalMemoryExtensionName* = "VK_EXT_pageable_device_local_memory"


# VK_EXT_pageable_device_local_memory
# ===================================
proc setDeviceMemoryPriorityEXT*(
      device: Device;
      memory: DeviceMemory;
      priority: float32;
    ): void {.lazyload("vkSetDeviceMemoryPriorityEXT", DeviceLevel).}


proc loadAllVK_EXT_pageable_device_local_memory*(instance: Instance) = instance.loadCommands:
  setDeviceMemoryPriorityEXT
proc loadVK_EXT_pageable_device_local_memory*(device: Device) = device.loadCommands:
  setDeviceMemoryPriorityEXT