# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_debug_marker

import ../tools
const
  # VK_EXT_debug_marker
  ExtDebugMarkerSpecVersion* = 4
  ExtDebugMarkerExtensionName* = "VK_EXT_debug_marker"


# VK_EXT_debug_marker
# ===================
proc debugMarkerSetObjectTagEXT*(
      device: Device;
      pTagInfo: ptr DebugMarkerObjectTagInfoEXT;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      lazyload("vkDebugMarkerSetObjectTagEXT", DeviceLevel).}
proc debugMarkerSetObjectNameEXT*(
      device: Device;
      pNameInfo: ptr DebugMarkerObjectNameInfoEXT;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      lazyload("vkDebugMarkerSetObjectNameEXT", DeviceLevel).}
proc cmdDebugMarkerBeginEXT*(
      commandBuffer: CommandBuffer;
      pMarkerInfo: ptr DebugMarkerMarkerInfoEXT;
    ): void {.cdecl, lazyload("vkCmdDebugMarkerBeginEXT", DeviceLevel).}
proc cmdDebugMarkerEndEXT*(
      commandBuffer: CommandBuffer;
    ): void {.cdecl, lazyload("vkCmdDebugMarkerEndEXT", DeviceLevel).}
proc cmdDebugMarkerInsertEXT*(
      commandBuffer: CommandBuffer;
      pMarkerInfo: ptr DebugMarkerMarkerInfoEXT;
    ): void {.cdecl, lazyload("vkCmdDebugMarkerInsertEXT", DeviceLevel).}


proc loadAllVK_EXT_debug_marker*(instance: Instance) = instance.loadCommands:
  debugMarkerSetObjectTagEXT
  debugMarkerSetObjectNameEXT
  cmdDebugMarkerBeginEXT
  cmdDebugMarkerEndEXT
  cmdDebugMarkerInsertEXT
proc loadVK_EXT_debug_marker*(device: Device) = device.loadCommands:
  debugMarkerSetObjectTagEXT
  debugMarkerSetObjectNameEXT
  cmdDebugMarkerBeginEXT
  cmdDebugMarkerEndEXT
  cmdDebugMarkerInsertEXT