# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_primitive_topology_list_restart

const
  # VK_EXT_primitive_topology_list_restart
  ExtPrimitiveTopologyListRestartSpecVersion* = 1
  ExtPrimitiveTopologyListRestartExtensionName* = "VK_EXT_primitive_topology_list_restart"

