# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_external_memory_host

import ../tools
const
  # VK_EXT_external_memory_host
  ExtExternalMemoryHostSpecVersion* = 1
  ExtExternalMemoryHostExtensionName* = "VK_EXT_external_memory_host"


# VK_EXT_external_memory_host
# ===========================
proc getMemoryHostPointerPropertiesEXT*(
      device: Device;
      handleType: ExternalMemoryHandleTypeFlagBits;
      pHostPointer: pointer;
      pMemoryHostPointerProperties: ptr MemoryHostPointerPropertiesEXT;
    ): Result {.lazyload("vkGetMemoryHostPointerPropertiesEXT", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorInvalidExternalHandle].}


proc loadAllVK_EXT_external_memory_host*(instance: Instance) = instance.loadCommands:
  getMemoryHostPointerPropertiesEXT
proc loadVK_EXT_external_memory_host*(device: Device) = device.loadCommands:
  getMemoryHostPointerPropertiesEXT