# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_extended_dynamic_state2

import ../tools
const
  # VK_EXT_extended_dynamic_state2
  ExtExtendedDynamicState2SpecVersion* = 1
  ExtExtendedDynamicState2ExtensionName* = "VK_EXT_extended_dynamic_state2"


# VK_EXT_extended_dynamic_state2
# ==============================
proc cmdSetPatchControlPointsEXT*(
      commandBuffer: CommandBuffer;
      patchControlPoints: uint32;
    ): void {.lazyload("vkCmdSetPatchControlPointsEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdSetRasterizerDiscardEnableEXT*(
      commandBuffer: CommandBuffer;
      rasterizerDiscardEnable: Bool32;
    ): void {.lazyload("vkCmdSetRasterizerDiscardEnableEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdSetDepthBiasEnableEXT*(
      commandBuffer: CommandBuffer;
      depthBiasEnable: Bool32;
    ): void {.lazyload("vkCmdSetDepthBiasEnableEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdSetLogicOpEXT*(
      commandBuffer: CommandBuffer;
      logicOp: LogicOp;
    ): void {.lazyload("vkCmdSetLogicOpEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdSetPrimitiveRestartEnableEXT*(
      commandBuffer: CommandBuffer;
      primitiveRestartEnable: Bool32;
    ): void {.lazyload("vkCmdSetPrimitiveRestartEnableEXT", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}


proc loadAllVK_EXT_extended_dynamic_state2*(instance: Instance) = instance.loadCommands:
  cmdSetPatchControlPointsEXT
  cmdSetRasterizerDiscardEnableEXT
  cmdSetDepthBiasEnableEXT
  cmdSetLogicOpEXT
  cmdSetPrimitiveRestartEnableEXT
proc loadVK_EXT_extended_dynamic_state2*(device: Device) = device.loadCommands:
  cmdSetPatchControlPointsEXT
  cmdSetRasterizerDiscardEnableEXT
  cmdSetDepthBiasEnableEXT
  cmdSetLogicOpEXT
  cmdSetPrimitiveRestartEnableEXT