# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_shader_atomic_float2

const
  # VK_EXT_shader_atomic_float2
  ExtShaderAtomicFloat2SpecVersion* = 1
  ExtShaderAtomicFloat2ExtensionName* = "VK_EXT_shader_atomic_float2"

