# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_inline_uniform_block

const
  # VK_EXT_inline_uniform_block
  ExtInlineUniformBlockSpecVersion* = 1
  ExtInlineUniformBlockExtensionName* = "VK_EXT_inline_uniform_block"

