# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_provoking_vertex

const
  # VK_EXT_provoking_vertex
  ExtProvokingVertexSpecVersion* = 1
  ExtProvokingVertexExtensionName* = "VK_EXT_provoking_vertex"

