# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_global_priority_query

const
  # VK_EXT_global_priority_query
  ExtGlobalPriorityQuerySpecVersion* = 1
  ExtGlobalPriorityQueryExtensionName* = "VK_EXT_global_priority_query"

