# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_vertex_input_dynamic_state

import ../tools
const
  # VK_EXT_vertex_input_dynamic_state
  ExtVertexInputDynamicStateSpecVersion* = 2
  ExtVertexInputDynamicStateExtensionName* = "VK_EXT_vertex_input_dynamic_state"


# VK_EXT_vertex_input_dynamic_state
# =================================
proc cmdSetVertexInputEXT*(
      commandBuffer: CommandBuffer;
      vertexBindingDescriptionCount = default(uint32);
      pVertexBindingDescriptions {.length: vertexBindingDescriptionCount.}: arrPtr[VertexInputBindingDescription2EXT];
      vertexAttributeDescriptionCount = default(uint32);
      pVertexAttributeDescriptions {.length: vertexAttributeDescriptionCount.}: arrPtr[VertexInputAttributeDescription2EXT];
    ): void {.lazyload("vkCmdSetVertexInputEXT", DeviceLevel), cmdchain.}


proc loadAllVK_EXT_vertex_input_dynamic_state*(instance: Instance) = instance.loadCommands:
  cmdSetVertexInputEXT
proc loadVK_EXT_vertex_input_dynamic_state*(device: Device) = device.loadCommands:
  cmdSetVertexInputEXT