# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_extended_dynamic_state2

import ../tools
const
  # VK_EXT_extended_dynamic_state2
  ExtExtendedDynamicState2SpecVersion* = 1
  ExtExtendedDynamicState2ExtensionName* = "VK_EXT_extended_dynamic_state2"


# VK_EXT_extended_dynamic_state2
# ==============================
proc cmdSetPatchControlPointsEXT*(
      commandBuffer: CommandBuffer;
      patchControlPoints: uint32;
    ): void {.cdecl, lazyload("vkCmdSetPatchControlPointsEXT", DeviceLevel).}
proc cmdSetRasterizerDiscardEnableEXT*(
      commandBuffer: CommandBuffer;
      rasterizerDiscardEnable: Bool32;
    ): void {.cdecl, lazyload("vkCmdSetRasterizerDiscardEnableEXT", DeviceLevel).}
proc cmdSetDepthBiasEnableEXT*(
      commandBuffer: CommandBuffer;
      depthBiasEnable: Bool32;
    ): void {.cdecl, lazyload("vkCmdSetDepthBiasEnableEXT", DeviceLevel).}
proc cmdSetLogicOpEXT*(
      commandBuffer: CommandBuffer;
      logicOp: LogicOp;
    ): void {.cdecl, lazyload("vkCmdSetLogicOpEXT", DeviceLevel).}
proc cmdSetPrimitiveRestartEnableEXT*(
      commandBuffer: CommandBuffer;
      primitiveRestartEnable: Bool32;
    ): void {.cdecl, lazyload("vkCmdSetPrimitiveRestartEnableEXT", DeviceLevel).}


proc loadAllVK_EXT_extended_dynamic_state2*(instance: Instance) = instance.loadCommands:
  cmdSetPatchControlPointsEXT
  cmdSetRasterizerDiscardEnableEXT
  cmdSetDepthBiasEnableEXT
  cmdSetLogicOpEXT
  cmdSetPrimitiveRestartEnableEXT
proc loadVK_EXT_extended_dynamic_state2*(device: Device) = device.loadCommands:
  cmdSetPatchControlPointsEXT
  cmdSetRasterizerDiscardEnableEXT
  cmdSetDepthBiasEnableEXT
  cmdSetLogicOpEXT
  cmdSetPrimitiveRestartEnableEXT