# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_conditional_rendering

import ../tools
const
  # VK_EXT_conditional_rendering
  ExtConditionalRenderingSpecVersion* = 2
  ExtConditionalRenderingExtensionName* = "VK_EXT_conditional_rendering"


# VK_EXT_conditional_rendering
# ============================
proc cmdBeginConditionalRenderingEXT*(
      commandBuffer: CommandBuffer;
      pConditionalRenderingBegin: ptr ConditionalRenderingBeginInfoEXT;
    ): void {.lazyload("vkCmdBeginConditionalRenderingEXT", DeviceLevel), cmdchain.}
proc cmdEndConditionalRenderingEXT*(
      commandBuffer: CommandBuffer;
    ): void {.lazyload("vkCmdEndConditionalRenderingEXT", DeviceLevel), cmdchain.}


proc loadAllVK_EXT_conditional_rendering*(instance: Instance) = instance.loadCommands:
  cmdBeginConditionalRenderingEXT
  cmdEndConditionalRenderingEXT
proc loadVK_EXT_conditional_rendering*(device: Device) = device.loadCommands:
  cmdBeginConditionalRenderingEXT
  cmdEndConditionalRenderingEXT