# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_host_query_reset

const
  # VK_EXT_host_query_reset
  ExtHostQueryResetSpecVersion* = 1
  ExtHostQueryResetExtensionName* = "VK_EXT_host_query_reset"


# VK_EXT_host_query_reset
# =======================
template resetQueryPoolEXT* = resetQueryPool

