# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_tooling_info

import ../tools
const
  # VK_EXT_tooling_info
  ExtToolingInfoSpecVersion* = 1
  ExtToolingInfoExtensionName* = "VK_EXT_tooling_info"


# VK_EXT_tooling_info
# ===================
proc getPhysicalDeviceToolPropertiesEXT*(
      physicalDevice: PhysicalDevice;
      pToolCount: ptr uint32;
      pToolProperties {.length: pToolCount.} = default(arrPtr[PhysicalDeviceToolPropertiesEXT]);
    ): Result {.cdecl,
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory],
      lazyload("vkGetPhysicalDeviceToolPropertiesEXT", InstanceLevel).}


proc loadAllVK_EXT_tooling_info*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceToolPropertiesEXT
proc loadVK_EXT_tooling_info*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceToolPropertiesEXT