# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_video_decode_h265

const
  # VK_EXT_video_decode_h265
  ExtVideoDecodeH265SpecVersion* = 1
  ExtVideoDecodeH265ExtensionName* = "VK_EXT_video_decode_h265"

