# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_ycbcr_2plane_444_formats

const
  # VK_EXT_ycbcr_2plane_444_formats
  ExtYcbcr2plane444FormatsSpecVersion* = 1
  ExtYcbcr2plane444FormatsExtensionName* = "VK_EXT_ycbcr_2plane_444_formats"

