# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_discard_rectangles

import ../tools
const
  # VK_EXT_discard_rectangles
  ExtDiscardRectanglesSpecVersion* = 1
  ExtDiscardRectanglesExtensionName* = "VK_EXT_discard_rectangles"


# VK_EXT_discard_rectangles
# =========================
proc cmdSetDiscardRectangleEXT*(
      commandBuffer: CommandBuffer;
      firstDiscardRectangle: uint32;
      discardRectangleCount: uint32;
      pDiscardRectangles {.length: discardRectangleCount.}: arrPtr[Rect2D];
    ): void {.lazyload("vkCmdSetDiscardRectangleEXT", DeviceLevel), cmdchain.}


proc loadAllVK_EXT_discard_rectangles*(instance: Instance) = instance.loadCommands:
  cmdSetDiscardRectangleEXT
proc loadVK_EXT_discard_rectangles*(device: Device) = device.loadCommands:
  cmdSetDiscardRectangleEXT