# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_rgba10x6_formats

const
  # VK_EXT_rgba10x6_formats
  ExtRgba10x6FormatsSpecVersion* = 1
  ExtRgba10x6FormatsExtensionName* = "VK_EXT_rgba10x6_formats"

