# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_depth_clip_control

const
  # VK_EXT_depth_clip_control
  ExtDepthClipControlSpecVersion* = 1
  ExtDepthClipControlExtensionName* = "VK_EXT_depth_clip_control"

