# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_GOOGLE_surfaceless_query

const
  # VK_GOOGLE_surfaceless_query
  GoogleSurfacelessQuerySpecVersion* = 1
  GoogleSurfacelessQueryExtensionName* = "VK_GOOGLE_surfaceless_query"

