# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_GOOGLE_hlsl_functionality1

const
  # VK_GOOGLE_hlsl_functionality1
  GoogleHlslFunctionality1SpecVersion* = 1
  GoogleHlslFunctionality1ExtensionName* = "VK_GOOGLE_hlsl_functionality1"

