# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_HUAWEI_invocation_mask

import ../tools
const
  # VK_HUAWEI_invocation_mask
  HuaweiInvocationMaskSpecVersion* = 1
  HuaweiInvocationMaskExtensionName* = "VK_HUAWEI_invocation_mask"


# VK_HUAWEI_invocation_mask
# =========================
proc cmdBindInvocationMaskHUAWEI*(
      commandBuffer: CommandBuffer;
      imageView = default(ImageView);
      imageLayout: ImageLayout;
    ): void {.lazyload("vkCmdBindInvocationMaskHUAWEI", DeviceLevel), cmdchain.}


proc loadAllVK_HUAWEI_invocation_mask*(instance: Instance) = instance.loadCommands:
  cmdBindInvocationMaskHUAWEI
proc loadVK_HUAWEI_invocation_mask*(device: Device) = device.loadCommands:
  cmdBindInvocationMaskHUAWEI