# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_IMG_format_pvrtc

const
  # VK_IMG_format_pvrtc
  ImgFormatPvrtcSpecVersion* = 1
  ImgFormatPvrtcExtensionName* = "VK_IMG_format_pvrtc"

