# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_INTEL_performance_query

import ../tools
const
  # VK_INTEL_performance_query
  IntelPerformanceQuerySpecVersion* = 2
  IntelPerformanceQueryExtensionName* = "VK_INTEL_performance_query"


# VK_INTEL_performance_query
# ==========================
proc initializePerformanceApiINTEL*(
      device: Device;
      pInitializeInfo: ptr InitializePerformanceApiInfoINTEL;
    ): Result {.lazyload("vkInitializePerformanceApiINTEL", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc uninitializePerformanceApiINTEL*(
      device: Device;
    ): void {.lazyload("vkUninitializePerformanceApiINTEL", DeviceLevel).}
proc cmdSetPerformanceMarkerINTEL*(
      commandBuffer: CommandBuffer;
      pMarkerInfo: ptr PerformanceMarkerInfoINTEL;
    ): Result {.lazyload("vkCmdSetPerformanceMarkerINTEL", DeviceLevel),
      queues: QueueFlags{graphics, compute, transfer}, cmdchain,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc cmdSetPerformanceStreamMarkerINTEL*(
      commandBuffer: CommandBuffer;
      pMarkerInfo: ptr PerformanceStreamMarkerInfoINTEL;
    ): Result {.lazyload("vkCmdSetPerformanceStreamMarkerINTEL", DeviceLevel),
      queues: QueueFlags{graphics, compute, transfer}, cmdchain,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc cmdSetPerformanceOverrideINTEL*(
      commandBuffer: CommandBuffer;
      pOverrideInfo: ptr PerformanceOverrideInfoINTEL;
    ): Result {.lazyload("vkCmdSetPerformanceOverrideINTEL", DeviceLevel),
      queues: QueueFlags{graphics, compute, transfer}, cmdchain,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc acquirePerformanceConfigurationINTEL*(
      device: Device;
      pAcquireInfo: ptr PerformanceConfigurationAcquireInfoINTEL;
      pConfiguration: ptr PerformanceConfigurationINTEL;
    ): Result {.lazyload("vkAcquirePerformanceConfigurationINTEL", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc releasePerformanceConfigurationINTEL*(
      device: Device;
      configuration = default(PerformanceConfigurationINTEL);
    ): Result {.lazyload("vkReleasePerformanceConfigurationINTEL", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc queueSetPerformanceConfigurationINTEL*(
      queue: Queue;
      configuration: PerformanceConfigurationINTEL;
    ): Result {.lazyload("vkQueueSetPerformanceConfigurationINTEL", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}
proc getPerformanceParameterINTEL*(
      device: Device;
      parameter: PerformanceParameterTypeINTEL;
      pValue: ptr PerformanceValueINTEL;
    ): Result {.lazyload("vkGetPerformanceParameterINTEL", DeviceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory].}


proc loadAllVK_INTEL_performance_query*(instance: Instance) = instance.loadCommands:
  initializePerformanceApiINTEL
  uninitializePerformanceApiINTEL
  cmdSetPerformanceMarkerINTEL
  cmdSetPerformanceStreamMarkerINTEL
  cmdSetPerformanceOverrideINTEL
  acquirePerformanceConfigurationINTEL
  releasePerformanceConfigurationINTEL
  queueSetPerformanceConfigurationINTEL
  getPerformanceParameterINTEL
proc loadVK_INTEL_performance_query*(device: Device) = device.loadCommands:
  initializePerformanceApiINTEL
  uninitializePerformanceApiINTEL
  cmdSetPerformanceMarkerINTEL
  cmdSetPerformanceStreamMarkerINTEL
  cmdSetPerformanceOverrideINTEL
  acquirePerformanceConfigurationINTEL
  releasePerformanceConfigurationINTEL
  queueSetPerformanceConfigurationINTEL
  getPerformanceParameterINTEL