# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_IMG_filter_cubic

const
  # VK_IMG_filter_cubic
  ImgFilterCubicSpecVersion* = 1
  ImgFilterCubicExtensionName* = "VK_IMG_filter_cubic"

