# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_INTEL_shader_integer_functions2

const
  # VK_INTEL_shader_integer_functions2
  IntelShaderIntegerFunctions2SpecVersion* = 1
  IntelShaderIntegerFunctions2ExtensionName* = "VK_INTEL_shader_integer_functions2"

