# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_ray_query

const
  # VK_KHR_ray_query
  KhrRayQuerySpecVersion* = 1
  KhrRayQueryExtensionName* = "VK_KHR_ray_query"

