# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_sampler_mirror_clamp_to_edge

const
  # VK_KHR_sampler_mirror_clamp_to_edge
  KhrSamplerMirrorClampToEdgeSpecVersion* = 3
  KhrSamplerMirrorClampToEdgeExtensionName* = "VK_KHR_sampler_mirror_clamp_to_edge"
  SamplerAddressModeMirrorClampToEdge* = 4

