# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_copy_commands2

import ../tools
const
  # VK_KHR_copy_commands2
  KhrCopyCommands2SpecVersion* = 1
  KhrCopyCommands2ExtensionName* = "VK_KHR_copy_commands2"


# VK_KHR_copy_commands2
# =====================
proc cmdCopyBuffer2KHR*(
      commandBuffer: CommandBuffer;
      pCopyBufferInfo: ptr CopyBufferInfo2KHR;
    ): void {.lazyload("vkCmdCopyBuffer2KHR", DeviceLevel),
      queues: QueueFlags{transfer, graphics, compute}, cmdchain.}
proc cmdCopyImage2KHR*(
      commandBuffer: CommandBuffer;
      pCopyImageInfo: ptr CopyImageInfo2KHR;
    ): void {.lazyload("vkCmdCopyImage2KHR", DeviceLevel),
      queues: QueueFlags{transfer, graphics, compute}, cmdchain.}
proc cmdCopyBufferToImage2KHR*(
      commandBuffer: CommandBuffer;
      pCopyBufferToImageInfo: ptr CopyBufferToImageInfo2KHR;
    ): void {.lazyload("vkCmdCopyBufferToImage2KHR", DeviceLevel),
      queues: QueueFlags{transfer, graphics, compute}, cmdchain.}
proc cmdCopyImageToBuffer2KHR*(
      commandBuffer: CommandBuffer;
      pCopyImageToBufferInfo: ptr CopyImageToBufferInfo2KHR;
    ): void {.lazyload("vkCmdCopyImageToBuffer2KHR", DeviceLevel),
      queues: QueueFlags{transfer, graphics, compute}, cmdchain.}
proc cmdBlitImage2KHR*(
      commandBuffer: CommandBuffer;
      pBlitImageInfo: ptr BlitImageInfo2KHR;
    ): void {.lazyload("vkCmdBlitImage2KHR", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}
proc cmdResolveImage2KHR*(
      commandBuffer: CommandBuffer;
      pResolveImageInfo: ptr ResolveImageInfo2KHR;
    ): void {.lazyload("vkCmdResolveImage2KHR", DeviceLevel),
      queues: QueueFlags{graphics}, cmdchain.}


proc loadAllVK_KHR_copy_commands2*(instance: Instance) = instance.loadCommands:
  cmdCopyBuffer2KHR
  cmdCopyImage2KHR
  cmdCopyBufferToImage2KHR
  cmdCopyImageToBuffer2KHR
  cmdBlitImage2KHR
  cmdResolveImage2KHR
proc loadVK_KHR_copy_commands2*(device: Device) = device.loadCommands:
  cmdCopyBuffer2KHR
  cmdCopyImage2KHR
  cmdCopyBufferToImage2KHR
  cmdCopyImageToBuffer2KHR
  cmdBlitImage2KHR
  cmdResolveImage2KHR