# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_zero_initialize_workgroup_memory

const
  # VK_KHR_zero_initialize_workgroup_memory
  KhrZeroInitializeWorkgroupMemorySpecVersion* = 1
  KhrZeroInitializeWorkgroupMemoryExtensionName* = "VK_KHR_zero_initialize_workgroup_memory"

