# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_storage_buffer_storage_class

const
  # VK_KHR_storage_buffer_storage_class
  KhrStorageBufferStorageClassSpecVersion* = 1
  KhrStorageBufferStorageClassExtensionName* = "VK_KHR_storage_buffer_storage_class"

