# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_video_encode_queue

import ../tools
const
  # VK_KHR_video_encode_queue
  KhrVideoEncodeQueueSpecVersion* = 3
  KhrVideoEncodeQueueExtensionName* = "VK_KHR_video_encode_queue"


# VK_KHR_video_encode_queue
# =========================
proc cmdEncodeVideoKHR*(
      commandBuffer: CommandBuffer;
      pEncodeInfo: ptr VideoEncodeInfoKHR;
    ): void {.cdecl, lazyload("vkCmdEncodeVideoKHR", DeviceLevel).}


proc loadAllVK_KHR_video_encode_queue*(instance: Instance) = instance.loadCommands:
  cmdEncodeVideoKHR
proc loadVK_KHR_video_encode_queue*(device: Device) = device.loadCommands:
  cmdEncodeVideoKHR