# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_vulkan_memory_model

const
  # VK_KHR_vulkan_memory_model
  KhrVulkanMemoryModelSpecVersion* = 3
  KhrVulkanMemoryModelExtensionName* = "VK_KHR_vulkan_memory_model"

