# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_terminate_invocation

const
  # VK_KHR_shader_terminate_invocation
  KhrShaderTerminateInvocationSpecVersion* = 1
  KhrShaderTerminateInvocationExtensionName* = "VK_KHR_shader_terminate_invocation"

