# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_image_format_list

const
  # VK_KHR_image_format_list
  KhrImageFormatListSpecVersion* = 1
  KhrImageFormatListExtensionName* = "VK_KHR_image_format_list"

