# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_timeline_semaphore

const
  # VK_KHR_timeline_semaphore
  KhrTimelineSemaphoreSpecVersion* = 2
  KhrTimelineSemaphoreExtensionName* = "VK_KHR_timeline_semaphore"


# VK_KHR_timeline_semaphore
# =========================
template getSemaphoreCounterValueKHR* = getSemaphoreCounterValue
template waitSemaphoresKHR* = waitSemaphores
template signalSemaphoreKHR* = signalSemaphore

