# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_mir_surface

const
  # VK_KHR_mir_surface
  KhrMirSurfaceSpecVersion* = 4
  KhrMirSurfaceExtensionName* = "VK_KHR_mir_surface"

