# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_descriptor_update_template

import ../tools
const
  # VK_KHR_descriptor_update_template
  KhrDescriptorUpdateTemplateSpecVersion* = 1
  KhrDescriptorUpdateTemplateExtensionName* = "VK_KHR_descriptor_update_template"
  DescriptorUpdateTemplateTypePushDescriptorsKhr* = 1


# VK_KHR_descriptor_update_template
# =================================
template createDescriptorUpdateTemplateKHR* = createDescriptorUpdateTemplate
template destroyDescriptorUpdateTemplateKHR* = destroyDescriptorUpdateTemplate
template updateDescriptorSetWithTemplateKHR* = updateDescriptorSetWithTemplate
proc cmdPushDescriptorSetWithTemplateKHR*(
      commandBuffer: CommandBuffer;
      descriptorUpdateTemplate: DescriptorUpdateTemplate;
      layout: PipelineLayout;
      set: uint32;
      pData: pointer;
    ): void {.lazyload("vkCmdPushDescriptorSetWithTemplateKHR", DeviceLevel),
      queues: QueueFlags{graphics, compute}, cmdchain.}


proc loadAllVK_KHR_descriptor_update_template*(instance: Instance) = instance.loadCommands:
  cmdPushDescriptorSetWithTemplateKHR
proc loadVK_KHR_descriptor_update_template*(device: Device) = device.loadCommands:
  cmdPushDescriptorSetWithTemplateKHR