# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_non_semantic_info

const
  # VK_KHR_shader_non_semantic_info
  KhrShaderNonSemanticInfoSpecVersion* = 1
  KhrShaderNonSemanticInfoExtensionName* = "VK_KHR_shader_non_semantic_info"

