# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_external_fence_capabilities

const
  # VK_KHR_external_fence_capabilities
  KhrExternalFenceCapabilitiesSpecVersion* = 1
  KhrExternalFenceCapabilitiesExtensionName* = "VK_KHR_external_fence_capabilities"


# VK_KHR_external_fence_capabilities
# ==================================
template getPhysicalDeviceExternalFencePropertiesKHR* = getPhysicalDeviceExternalFenceProperties

