# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_draw_parameters

const
  # VK_KHR_shader_draw_parameters
  KhrShaderDrawParametersSpecVersion* = 1
  KhrShaderDrawParametersExtensionName* = "VK_KHR_shader_draw_parameters"

