# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_device_group_creation

const
  # VK_KHR_device_group_creation
  KhrDeviceGroupCreationSpecVersion* = 1
  KhrDeviceGroupCreationExtensionName* = "VK_KHR_device_group_creation"


# VK_KHR_device_group_creation
# ============================
template enumeratePhysicalDeviceGroupsKHR* = enumeratePhysicalDeviceGroups

