# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_bind_memory2

const
  # VK_KHR_bind_memory2
  KhrBindMemory2SpecVersion* = 1
  KhrBindMemory2ExtensionName* = "VK_KHR_bind_memory2"


# VK_KHR_bind_memory2
# ===================
template bindBufferMemory2KHR* = bindBufferMemory2
template bindImageMemory2KHR* = bindImageMemory2

