# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_pipeline_executable_properties

import ../tools
const
  # VK_KHR_pipeline_executable_properties
  KhrPipelineExecutablePropertiesSpecVersion* = 1
  KhrPipelineExecutablePropertiesExtensionName* = "VK_KHR_pipeline_executable_properties"


# VK_KHR_pipeline_executable_properties
# =====================================
proc getPipelineExecutablePropertiesKHR*(
      device: Device;
      pPipelineInfo: ptr PipelineInfoKHR;
      pExecutableCount: ptr uint32;
      pProperties {.length: pExecutableCount.} = default(arrPtr[PipelineExecutablePropertiesKHR]);
    ): Result {.cdecl,
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      lazyload("vkGetPipelineExecutablePropertiesKHR", DeviceLevel).}
proc getPipelineExecutableStatisticsKHR*(
      device: Device;
      pExecutableInfo: ptr PipelineExecutableInfoKHR;
      pStatisticCount: ptr uint32;
      pStatistics {.length: pStatisticCount.} = default(arrPtr[PipelineExecutableStatisticKHR]);
    ): Result {.cdecl,
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      lazyload("vkGetPipelineExecutableStatisticsKHR", DeviceLevel).}
proc getPipelineExecutableInternalRepresentationsKHR*(
      device: Device;
      pExecutableInfo: ptr PipelineExecutableInfoKHR;
      pInternalRepresentationCount: ptr uint32;
      pInternalRepresentations {.length: pInternalRepresentationCount.} = default(arrPtr[PipelineExecutableInternalRepresentationKHR]);
    ): Result {.cdecl,
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      lazyload("vkGetPipelineExecutableInternalRepresentationsKHR", DeviceLevel).}


proc loadAllVK_KHR_pipeline_executable_properties*(instance: Instance) = instance.loadCommands:
  getPipelineExecutablePropertiesKHR
  getPipelineExecutableStatisticsKHR
  getPipelineExecutableInternalRepresentationsKHR
proc loadVK_KHR_pipeline_executable_properties*(device: Device) = device.loadCommands:
  getPipelineExecutablePropertiesKHR
  getPipelineExecutableStatisticsKHR
  getPipelineExecutableInternalRepresentationsKHR