# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_present_id

const
  # VK_KHR_present_id
  KhrPresentIdSpecVersion* = 1
  KhrPresentIdExtensionName* = "VK_KHR_present_id"

