# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_spirv_1_4

const
  # VK_KHR_spirv_1_4
  KhrSpirv14SpecVersion* = 1
  KhrSpirv14ExtensionName* = "VK_KHR_spirv_1_4"

