# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_subgroup_uniform_control_flow

const
  # VK_KHR_shader_subgroup_uniform_control_flow
  KhrShaderSubgroupUniformControlFlowSpecVersion* = 1
  KhrShaderSubgroupUniformControlFlowExtensionName* = "VK_KHR_shader_subgroup_uniform_control_flow"

