# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_buffer_device_address

const
  # VK_KHR_buffer_device_address
  KhrBufferDeviceAddressSpecVersion* = 1
  KhrBufferDeviceAddressExtensionName* = "VK_KHR_buffer_device_address"


# VK_KHR_buffer_device_address
# ============================
template getBufferDeviceAddressKHR* = getBufferDeviceAddress
template getBufferOpaqueCaptureAddressKHR* = getBufferOpaqueCaptureAddress
template getDeviceMemoryOpaqueCaptureAddressKHR* = getDeviceMemoryOpaqueCaptureAddress

