# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_subgroup_extended_types

const
  # VK_KHR_shader_subgroup_extended_types
  KhrShaderSubgroupExtendedTypesSpecVersion* = 1
  KhrShaderSubgroupExtendedTypesExtensionName* = "VK_KHR_shader_subgroup_extended_types"

