# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_external_memory_fd

import ../tools
const
  # VK_KHR_external_memory_fd
  KhrExternalMemoryFdSpecVersion* = 1
  KhrExternalMemoryFdExtensionName* = "VK_KHR_external_memory_fd"


# VK_KHR_external_memory_fd
# =========================
proc getMemoryFdKHR*(
      device: Device;
      pGetFdInfo: ptr MemoryGetFdInfoKHR;
      pFd: ptr int;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory],
      lazyload("vkGetMemoryFdKHR", DeviceLevel).}
proc getMemoryFdPropertiesKHR*(
      device: Device;
      handleType: ExternalMemoryHandleTypeFlagBits;
      fd: int;
      pMemoryFdProperties: ptr MemoryFdPropertiesKHR;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorInvalidExternalHandle],
      lazyload("vkGetMemoryFdPropertiesKHR", DeviceLevel).}


proc loadAllVK_KHR_external_memory_fd*(instance: Instance) = instance.loadCommands:
  getMemoryFdKHR
  getMemoryFdPropertiesKHR
proc loadVK_KHR_external_memory_fd*(device: Device) = device.loadCommands:
  getMemoryFdKHR
  getMemoryFdPropertiesKHR