# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_incremental_present

const
  # VK_KHR_incremental_present
  KhrIncrementalPresentSpecVersion* = 2
  KhrIncrementalPresentExtensionName* = "VK_KHR_incremental_present"

