# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_get_memory_requirements2

const
  # VK_KHR_get_memory_requirements2
  KhrGetMemoryRequirements2SpecVersion* = 1
  KhrGetMemoryRequirements2ExtensionName* = "VK_KHR_get_memory_requirements2"


# VK_KHR_get_memory_requirements2
# ===============================
template getImageMemoryRequirements2KHR* = getImageMemoryRequirements2
template getBufferMemoryRequirements2KHR* = getBufferMemoryRequirements2
template getImageSparseMemoryRequirements2KHR* = getImageSparseMemoryRequirements2

