# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_portability_subset

const
  # VK_KHR_portability_subset
  KhrPortabilitySubsetSpecVersion* = 1
  KhrPortabilitySubsetExtensionName* = "VK_KHR_portability_subset"

