# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_shader_integer_dot_product

const
  # VK_KHR_shader_integer_dot_product
  KhrShaderIntegerDotProductSpecVersion* = 1
  KhrShaderIntegerDotProductExtensionName* = "VK_KHR_shader_integer_dot_product"

