# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_present_wait

import ../tools
const
  # VK_KHR_present_wait
  KhrPresentWaitSpecVersion* = 1
  KhrPresentWaitExtensionName* = "VK_KHR_present_wait"


# VK_KHR_present_wait
# ===================
proc waitForPresentKHR*(
      device: Device;
      swapchain: SwapchainKHR;
      presentId: uint64;
      timeout: uint64;
    ): Result {.lazyload("vkWaitForPresentKHR", DeviceLevel),
      successCodes: @[Result.success, Result.timeout],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorDeviceLost].}


proc loadAllVK_KHR_present_wait*(instance: Instance) = instance.loadCommands:
  waitForPresentKHR
proc loadVK_KHR_present_wait*(device: Device) = device.loadCommands:
  waitForPresentKHR