# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_external_semaphore_fd

import ../tools
const
  # VK_KHR_external_semaphore_fd
  KhrExternalSemaphoreFdSpecVersion* = 1
  KhrExternalSemaphoreFdExtensionName* = "VK_KHR_external_semaphore_fd"


# VK_KHR_external_semaphore_fd
# ============================
proc importSemaphoreFdKHR*(
      device: Device;
      pImportSemaphoreFdInfo: ptr ImportSemaphoreFdInfoKHR;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorInvalidExternalHandle],
      lazyload("vkImportSemaphoreFdKHR", DeviceLevel).}
proc getSemaphoreFdKHR*(
      device: Device;
      pGetFdInfo: ptr SemaphoreGetFdInfoKHR;
      pFd: ptr int;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorTooManyObjects, Result.errorOutOfHostMemory],
      lazyload("vkGetSemaphoreFdKHR", DeviceLevel).}


proc loadAllVK_KHR_external_semaphore_fd*(instance: Instance) = instance.loadCommands:
  importSemaphoreFdKHR
  getSemaphoreFdKHR
proc loadVK_KHR_external_semaphore_fd*(device: Device) = device.loadCommands:
  importSemaphoreFdKHR
  getSemaphoreFdKHR