# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_relaxed_block_layout

const
  # VK_KHR_relaxed_block_layout
  KhrRelaxedBlockLayoutSpecVersion* = 1
  KhrRelaxedBlockLayoutExtensionName* = "VK_KHR_relaxed_block_layout"

