# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_format_feature_flags2

const
  # VK_KHR_format_feature_flags2
  KhrFormatFeatureFlags2SpecVersion* = 1
  KhrFormatFeatureFlags2ExtensionName* = "VK_KHR_format_feature_flags2"

