# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_get_physical_device_properties2

const
  # VK_KHR_get_physical_device_properties2
  KhrGetPhysicalDeviceProperties2SpecVersion* = 2
  KhrGetPhysicalDeviceProperties2ExtensionName* = "VK_KHR_get_physical_device_properties2"


# VK_KHR_get_physical_device_properties2
# ======================================
template getPhysicalDeviceFeatures2KHR* = getPhysicalDeviceFeatures2
template getPhysicalDeviceProperties2KHR* = getPhysicalDeviceProperties2
template getPhysicalDeviceFormatProperties2KHR* = getPhysicalDeviceFormatProperties2
template getPhysicalDeviceImageFormatProperties2KHR* = getPhysicalDeviceImageFormatProperties2
template getPhysicalDeviceQueueFamilyProperties2KHR* = getPhysicalDeviceQueueFamilyProperties2
template getPhysicalDeviceMemoryProperties2KHR* = getPhysicalDeviceMemoryProperties2
template getPhysicalDeviceSparseImageFormatProperties2KHR* = getPhysicalDeviceSparseImageFormatProperties2

