# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_MVK_moltenvk

const
  # VK_MVK_moltenvk
  MmoltenspecVersion* = 0
  MmoltenextensionName* = "VK_MVK_moltenvk"

