# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_linear_color_attachment

const
  # VK_NV_linear_color_attachment
  NvLinearColorAttachmentSpecVersion* = 1
  NvLinearColorAttachmentExtensionName* = "VK_NV_linear_color_attachment"

