# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_fragment_shading_rate_enums

import ../tools
const
  # VK_NV_fragment_shading_rate_enums
  NvFragmentShadingRateEnumsSpecVersion* = 1
  NvFragmentShadingRateEnumsExtensionName* = "VK_NV_fragment_shading_rate_enums"


# VK_NV_fragment_shading_rate_enums
# =================================
proc cmdSetFragmentShadingRateEnumNV*(
      commandBuffer: CommandBuffer;
      shadingRate: FragmentShadingRateNV;
      combinerOps: FragmentShadingRateCombinerOpKHR;
    ): void {.lazyload("vkCmdSetFragmentShadingRateEnumNV", DeviceLevel), cmdchain.}


proc loadAllVK_NV_fragment_shading_rate_enums*(instance: Instance) = instance.loadCommands:
  cmdSetFragmentShadingRateEnumNV
proc loadVK_NV_fragment_shading_rate_enums*(device: Device) = device.loadCommands:
  cmdSetFragmentShadingRateEnumNV