# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_external_memory_capabilities

import ../tools
const
  # VK_NV_external_memory_capabilities
  NvExternalMemoryCapabilitiesSpecVersion* = 1
  NvExternalMemoryCapabilitiesExtensionName* = "VK_NV_external_memory_capabilities"


# VK_NV_external_memory_capabilities
# ==================================
proc getPhysicalDeviceExternalImageFormatPropertiesNV*(
      physicalDevice: PhysicalDevice;
      format: Format;
      theType: ImageType;
      tiling: ImageTiling;
      usage: ImageUsageFlags;
      flags = default(ImageCreateFlags);
      externalHandleType = default(ExternalMemoryHandleTypeFlagsNV);
      pExternalImageFormatProperties: ptr ExternalImageFormatPropertiesNV;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorFormatNotSupported],
      lazyload("vkGetPhysicalDeviceExternalImageFormatPropertiesNV", InstanceLevel).}


proc loadAllVK_NV_external_memory_capabilities*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceExternalImageFormatPropertiesNV
proc loadVK_NV_external_memory_capabilities*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceExternalImageFormatPropertiesNV