# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_inherited_viewport_scissor

const
  # VK_NV_inherited_viewport_scissor
  NvInheritedViewportScissorSpecVersion* = 1
  NvInheritedViewportScissorExtensionName* = "VK_NV_inherited_viewport_scissor"

