# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_geometry_shader_passthrough

const
  # VK_NV_geometry_shader_passthrough
  NvGeometryShaderPassthroughSpecVersion* = 1
  NvGeometryShaderPassthroughExtensionName* = "VK_NV_geometry_shader_passthrough"

