# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NVX_multiview_per_view_attributes

const
  # VK_NVX_multiview_per_view_attributes
  NvxMultiviewPerViewAttributesSpecVersion* = 1
  NvxMultiviewPerViewAttributesExtensionName* = "VK_NVX_multiview_per_view_attributes"

