# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_coverage_reduction_mode

import ../tools
const
  # VK_NV_coverage_reduction_mode
  NvCoverageReductionModeSpecVersion* = 1
  NvCoverageReductionModeExtensionName* = "VK_NV_coverage_reduction_mode"


# VK_NV_coverage_reduction_mode
# =============================
proc getPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV*(
      physicalDevice: PhysicalDevice;
      pCombinationCount: ptr uint32;
      pCombinations {.length: pCombinationCount.} = default(arrPtr[FramebufferMixedSamplesCombinationNV]);
    ): Result {.lazyload("vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV", InstanceLevel),
      successCodes: @[Result.success, Result.incomplete],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}


proc loadAllVK_NV_coverage_reduction_mode*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV
proc loadVK_NV_coverage_reduction_mode*(instance: Instance) = instance.loadCommands:
  getPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV