# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_scissor_exclusive

import ../tools
const
  # VK_NV_scissor_exclusive
  NvScissorExclusiveSpecVersion* = 1
  NvScissorExclusiveExtensionName* = "VK_NV_scissor_exclusive"


# VK_NV_scissor_exclusive
# =======================
proc cmdSetExclusiveScissorNV*(
      commandBuffer: CommandBuffer;
      firstExclusiveScissor: uint32;
      exclusiveScissorCount: uint32;
      pExclusiveScissors {.length: exclusiveScissorCount.}: arrPtr[Rect2D];
    ): void {.lazyload("vkCmdSetExclusiveScissorNV", DeviceLevel), cmdchain.}


proc loadAllVK_NV_scissor_exclusive*(instance: Instance) = instance.loadCommands:
  cmdSetExclusiveScissorNV
proc loadVK_NV_scissor_exclusive*(device: Device) = device.loadCommands:
  cmdSetExclusiveScissorNV