# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_sample_mask_override_coverage

const
  # VK_NV_sample_mask_override_coverage
  NvSampleMaskOverrideCoverageSpecVersion* = 1
  NvSampleMaskOverrideCoverageExtensionName* = "VK_NV_sample_mask_override_coverage"

