# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_mesh_shader

import ../tools
const
  # VK_NV_mesh_shader
  NvMeshShaderSpecVersion* = 1
  NvMeshShaderExtensionName* = "VK_NV_mesh_shader"


# VK_NV_mesh_shader
# =================
proc cmdDrawMeshTasksNV*(
      commandBuffer: CommandBuffer;
      taskCount: uint32;
      firstTask: uint32;
    ): void {.lazyload("vkCmdDrawMeshTasksNV", DeviceLevel), cmdchain.}
proc cmdDrawMeshTasksIndirectNV*(
      commandBuffer: CommandBuffer;
      buffer: Buffer;
      offset: DeviceSize;
      drawCount: uint32;
      stride: uint32;
    ): void {.lazyload("vkCmdDrawMeshTasksIndirectNV", DeviceLevel), cmdchain.}
proc cmdDrawMeshTasksIndirectCountNV*(
      commandBuffer: CommandBuffer;
      buffer: Buffer;
      offset: DeviceSize;
      countBuffer: Buffer;
      countBufferOffset: DeviceSize;
      maxDrawCount: uint32;
      stride: uint32;
    ): void {.lazyload("vkCmdDrawMeshTasksIndirectCountNV", DeviceLevel), cmdchain.}


proc loadAllVK_NV_mesh_shader*(instance: Instance) = instance.loadCommands:
  cmdDrawMeshTasksNV
  cmdDrawMeshTasksIndirectNV
  cmdDrawMeshTasksIndirectCountNV
proc loadVK_NV_mesh_shader*(device: Device) = device.loadCommands:
  cmdDrawMeshTasksNV
  cmdDrawMeshTasksIndirectNV
  cmdDrawMeshTasksIndirectCountNV