# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_ray_tracing_motion_blur

const
  # VK_NV_ray_tracing_motion_blur
  NvRayTracingMotionBlurSpecVersion* = 1
  NvRayTracingMotionBlurExtensionName* = "VK_NV_ray_tracing_motion_blur"

