# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_shader_subgroup_partitioned

const
  # VK_NV_shader_subgroup_partitioned
  NvShaderSubgroupPartitionedSpecVersion* = 1
  NvShaderSubgroupPartitionedExtensionName* = "VK_NV_shader_subgroup_partitioned"

