# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NN_vi_surface

import ../tools
const
  # VK_NN_vi_surface
  NnViSurfaceSpecVersion* = 1
  NnViSurfaceExtensionName* = "VK_NN_vi_surface"


# VK_NN_vi_surface
# ================
proc createViSurfaceNN*(
      instance: Instance;
      pCreateInfo: ptr ViSurfaceCreateInfoNN;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorNativeWindowInUseKhr],
      lazyload("vkCreateViSurfaceNN", InstanceLevel).}


proc loadAllVK_NN_vi_surface*(instance: Instance) = instance.loadCommands:
  createViSurfaceNN
proc loadVK_NN_vi_surface*(instance: Instance) = instance.loadCommands:
  createViSurfaceNN