# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_NV_external_memory_rdma

import ../tools
const
  # VK_NV_external_memory_rdma
  NvExternalMemoryRdmaSpecVersion* = 1
  NvExternalMemoryRdmaExtensionName* = "VK_NV_external_memory_rdma"


# VK_NV_external_memory_rdma
# ==========================
proc getMemoryRemoteAddressNV*(
      device: Device;
      pMemoryGetRemoteAddressInfo: ptr MemoryGetRemoteAddressInfoNV;
      pAddress: ptr RemoteAddressNV;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorInvalidExternalHandle],
      lazyload("vkGetMemoryRemoteAddressNV", DeviceLevel).}


proc loadAllVK_NV_external_memory_rdma*(instance: Instance) = instance.loadCommands:
  getMemoryRemoteAddressNV
proc loadVK_NV_external_memory_rdma*(device: Device) = device.loadCommands:
  getMemoryRemoteAddressNV