# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_QCOM_render_pass_shader_resolve

const
  # VK_QCOM_render_pass_shader_resolve
  QcomRenderPassShaderResolveSpecVersion* = 4
  QcomRenderPassShaderResolveExtensionName* = "VK_QCOM_render_pass_shader_resolve"

