# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_QCOM_render_pass_store_ops

const
  # VK_QCOM_render_pass_store_ops
  QcomRenderPassStoreOpsSpecVersion* = 2
  QcomRenderPassStoreOpsExtensionName* = "VK_QCOM_render_pass_store_ops"

