# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_QCOM_rotated_copy_commands

const
  # VK_QCOM_rotated_copy_commands
  QcomRotatedCopyCommandsSpecVersion* = 1
  QcomRotatedCopyCommandsExtensionName* = "VK_QCOM_rotated_copy_commands"

