# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_QCOM_render_pass_transform

const
  # VK_QCOM_render_pass_transform
  QcomRenderPassTransformSpecVersion* = 2
  QcomRenderPassTransformExtensionName* = "VK_QCOM_render_pass_transform"

