# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.
type
  AHardwareBuffer* = distinct object
  Bool32* = distinct uint32
  Flags*[Flagbits] = distinct uint32
  CAMetalLayer* = distinct object
  DeviceSize* = distinct uint64
  SampleMask* = distinct uint32
  ANativeWindow* = distinct object
  DeviceAddress* = distinct uint64
