# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_MVK_ios_surface

import ../../tools
const
  # VK_MVK_ios_surface
  MiosSurfaceSpecVersion* = 3
  MiosSurfaceExtensionName* = "VK_MVK_ios_surface"


# VK_MVK_ios_surface
# ==================
proc createIOSSurfaceMVK*(
      instance: Instance;
      pCreateInfo: ptr IOSSurfaceCreateInfoMVK;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorNativeWindowInUseKhr],
      lazyload("vkCreateIOSSurfaceMVK", InstanceLevel).}


proc loadAllVK_MVK_ios_surface*(instance: Instance) = instance.loadCommands:
  createIOSSurfaceMVK
proc loadVK_MVK_ios_surface*(instance: Instance) = instance.loadCommands:
  createIOSSurfaceMVK