# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_KHR_xlib_surface
# VK_KHR_xcb_surface
# VK_KHR_wayland_surface
# VK_EXT_acquire_xlib_display

import ../../tools
const
  # VK_KHR_xlib_surface
  KhrXlibSurfaceSpecVersion* = 6
  KhrXlibSurfaceExtensionName* = "VK_KHR_xlib_surface"
  # VK_KHR_xcb_surface
  KhrXcbSurfaceSpecVersion* = 6
  KhrXcbSurfaceExtensionName* = "VK_KHR_xcb_surface"
  # VK_KHR_wayland_surface
  KhrWaylandSurfaceSpecVersion* = 6
  KhrWaylandSurfaceExtensionName* = "VK_KHR_wayland_surface"
  # VK_EXT_acquire_xlib_display
  ExtAcquireXlibDisplaySpecVersion* = 1
  ExtAcquireXlibDisplayExtensionName* = "VK_EXT_acquire_xlib_display"


# VK_KHR_xlib_surface
# ===================
proc createXlibSurfaceKHR*(
      instance: Instance;
      pCreateInfo: ptr XlibSurfaceCreateInfoKHR;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.lazyload("vkCreateXlibSurfaceKHR", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}
proc getPhysicalDeviceXlibPresentationSupportKHR*(
      physicalDevice: PhysicalDevice;
      queueFamilyIndex: uint32;
      dpy: ptr Display;
      visualID: VisualID;
    ): Bool32 {.lazyload("vkGetPhysicalDeviceXlibPresentationSupportKHR", InstanceLevel).}

# VK_KHR_xcb_surface
# ==================
proc createXcbSurfaceKHR*(
      instance: Instance;
      pCreateInfo: ptr XcbSurfaceCreateInfoKHR;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.lazyload("vkCreateXcbSurfaceKHR", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}
proc getPhysicalDeviceXcbPresentationSupportKHR*(
      physicalDevice: PhysicalDevice;
      queueFamilyIndex: uint32;
      connection: ptr XcbConnection;
      visual_id: XcbVisualid;
    ): Bool32 {.lazyload("vkGetPhysicalDeviceXcbPresentationSupportKHR", InstanceLevel).}

# VK_KHR_wayland_surface
# ======================
proc createWaylandSurfaceKHR*(
      instance: Instance;
      pCreateInfo: ptr WaylandSurfaceCreateInfoKHR;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.lazyload("vkCreateWaylandSurfaceKHR", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory].}
proc getPhysicalDeviceWaylandPresentationSupportKHR*(
      physicalDevice: PhysicalDevice;
      queueFamilyIndex: uint32;
      display: ptr wl_display;
    ): Bool32 {.lazyload("vkGetPhysicalDeviceWaylandPresentationSupportKHR", InstanceLevel).}

# VK_EXT_acquire_xlib_display
# ===========================
proc acquireXlibDisplayEXT*(
      physicalDevice: PhysicalDevice;
      dpy: ptr Display;
      display: DisplayKHR;
    ): Result {.lazyload("vkAcquireXlibDisplayEXT", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorInitializationFailed].}
proc getRandROutputDisplayEXT*(
      physicalDevice: PhysicalDevice;
      dpy: ptr Display;
      rrOutput: RROutput;
      pDisplay: ptr DisplayKHR;
    ): Result {.lazyload("vkGetRandROutputDisplayEXT", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory].}


proc loadAllVK_KHR_xlib_surface*(instance: Instance) = instance.loadCommands:
  createXlibSurfaceKHR
  getPhysicalDeviceXlibPresentationSupportKHR
proc loadAllVK_KHR_xcb_surface*(instance: Instance) = instance.loadCommands:
  createXcbSurfaceKHR
  getPhysicalDeviceXcbPresentationSupportKHR
proc loadAllVK_KHR_wayland_surface*(instance: Instance) = instance.loadCommands:
  createWaylandSurfaceKHR
  getPhysicalDeviceWaylandPresentationSupportKHR
proc loadAllVK_EXT_acquire_xlib_display*(instance: Instance) = instance.loadCommands:
  acquireXlibDisplayEXT
  getRandROutputDisplayEXT
proc loadVK_KHR_xlib_surface*(instance: Instance) = instance.loadCommands:
  createXlibSurfaceKHR
  getPhysicalDeviceXlibPresentationSupportKHR
proc loadVK_KHR_xcb_surface*(instance: Instance) = instance.loadCommands:
  createXcbSurfaceKHR
  getPhysicalDeviceXcbPresentationSupportKHR
proc loadVK_KHR_wayland_surface*(instance: Instance) = instance.loadCommands:
  createWaylandSurfaceKHR
  getPhysicalDeviceWaylandPresentationSupportKHR
proc loadVK_EXT_acquire_xlib_display*(instance: Instance) = instance.loadCommands:
  acquireXlibDisplayEXT
  getRandROutputDisplayEXT