# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_EXT_metal_surface

import ../../tools
const
  # VK_EXT_metal_surface
  ExtMetalSurfaceSpecVersion* = 1
  ExtMetalSurfaceExtensionName* = "VK_EXT_metal_surface"


# VK_EXT_metal_surface
# ====================
proc createMetalSurfaceEXT*(
      instance: Instance;
      pCreateInfo: ptr MetalSurfaceCreateInfoEXT;
      pAllocator = default(ptr AllocationCallbacks);
      pSurface: ptr SurfaceKHR;
    ): Result {.lazyload("vkCreateMetalSurfaceEXT", InstanceLevel),
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorNativeWindowInUseKhr].}


proc loadAllVK_EXT_metal_surface*(instance: Instance) = instance.loadCommands:
  createMetalSurfaceEXT
proc loadVK_EXT_metal_surface*(instance: Instance) = instance.loadCommands:
  createMetalSurfaceEXT