# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.

# VK_VERSION_1_2

import ../tools
const
  # VK_VERSION_1_2
  StructureTypePhysicalDeviceVulkan11Features* = 49
  StructureTypePhysicalDeviceVulkan11Properties* = 50
  StructureTypePhysicalDeviceVulkan12Features* = 51
  StructureTypePhysicalDeviceVulkan12Properties* = 52
  # Promoted from VK_KHR_sampler_mirror_clamp_to_edge (extension 15)
  SamplerAddressModeMirrorClampToEdge* = 4


# VK_VERSION_1_2
# ==============

template apiVersion12*(): untyped =
  makeApiVersion(0, 1, 2, 0)

# Promoted from VK_KHR_draw_indirect_count (extension 170)
proc cmdDrawIndirectCount*(
      commandBuffer: CommandBuffer;
      buffer: Buffer;
      offset: DeviceSize;
      countBuffer: Buffer;
      countBufferOffset: DeviceSize;
      maxDrawCount: uint32;
      stride: uint32;
    ): void {.cdecl, preload("vkCmdDrawIndirectCount").}
proc cmdDrawIndexedIndirectCount*(
      commandBuffer: CommandBuffer;
      buffer: Buffer;
      offset: DeviceSize;
      countBuffer: Buffer;
      countBufferOffset: DeviceSize;
      maxDrawCount: uint32;
      stride: uint32;
    ): void {.cdecl, preload("vkCmdDrawIndexedIndirectCount").}
# Promoted from VK_KHR_create_renderpass2 (extension 110)
proc createRenderPass2*(
      device: Device;
      pCreateInfo: ptr RenderPassCreateInfo2;
      pAllocator = default(ptr AllocationCallbacks);
      pRenderPass: ptr RenderPass;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      preload("vkCreateRenderPass2").}
proc cmdBeginRenderPass2*(
      commandBuffer: CommandBuffer;
      pRenderPassBegin: ptr RenderPassBeginInfo;
      pSubpassBeginInfo: ptr SubpassBeginInfo;
    ): void {.cdecl, preload("vkCmdBeginRenderPass2").}
proc cmdNextSubpass2*(
      commandBuffer: CommandBuffer;
      pSubpassBeginInfo: ptr SubpassBeginInfo;
      pSubpassEndInfo: ptr SubpassEndInfo;
    ): void {.cdecl, preload("vkCmdNextSubpass2").}
proc cmdEndRenderPass2*(
      commandBuffer: CommandBuffer;
      pSubpassEndInfo: ptr SubpassEndInfo;
    ): void {.cdecl, preload("vkCmdEndRenderPass2").}
# Promoted from VK_EXT_host_query_reset (extension 262)
proc resetQueryPool*(
      device: Device;
      queryPool: QueryPool;
      firstQuery: uint32;
      queryCount: uint32;
    ): void {.cdecl, preload("vkResetQueryPool").}
# Promoted from VK_KHR_timeline_semaphore (extension 208)
proc getSemaphoreCounterValue*(
      device: Device;
      semaphore: Semaphore;
      pValue: ptr uint64;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorDeviceLost],
      preload("vkGetSemaphoreCounterValue").}
proc waitSemaphores*(
      device: Device;
      pWaitInfo: ptr SemaphoreWaitInfo;
      timeout: uint64;
    ): Result {.cdecl,
      successCodes: @[Result.success, Result.timeout],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory, Result.errorDeviceLost],
      preload("vkWaitSemaphores").}
proc signalSemaphore*(
      device: Device;
      pSignalInfo: ptr SemaphoreSignalInfo;
    ): Result {.cdecl,
      successCodes: @[Result.success],
      errorCodes: @[Result.errorOutOfHostMemory, Result.errorOutOfDeviceMemory],
      preload("vkSignalSemaphore").}
# Promoted from VK_KHR_buffer_device_address (extension 258)
proc getBufferDeviceAddress*(
      device: Device;
      pInfo: ptr BufferDeviceAddressInfo;
    ): DeviceAddress {.cdecl, preload("vkGetBufferDeviceAddress").}
proc getBufferOpaqueCaptureAddress*(
      device: Device;
      pInfo: ptr BufferDeviceAddressInfo;
    ): uint64 {.cdecl, preload("vkGetBufferOpaqueCaptureAddress").}
proc getDeviceMemoryOpaqueCaptureAddress*(
      device: Device;
      pInfo: ptr DeviceMemoryOpaqueCaptureAddressInfo;
    ): uint64 {.cdecl, preload("vkGetDeviceMemoryOpaqueCaptureAddress").}

