# This file is generated by the program.
# Note that any changes to this file will be reset by the execution of
# the generated program.
import handleTypes
import handleOperations

type
  SurfaceKHR* = NonDispatchableHandle[HtSurfaceKHR]
  DisplayKHR* = NonDispatchableHandle[HtDisplayKHR]
  PipelineCache* = NonDispatchableHandle[HtPipelineCache]
  SwapchainKHR* = NonDispatchableHandle[HtSwapchainKHR]
  DebugReportCallbackEXT* = NonDispatchableHandle[HtDebugReportCallbackEXT]
  PipelineLayout* = NonDispatchableHandle[HtPipelineLayout]
  Device* = Handle[HtDevice]
  DescriptorPool* = NonDispatchableHandle[HtDescriptorPool]
  AccelerationStructureKHR* = NonDispatchableHandle[HtAccelerationStructureKHR]
  Buffer* = NonDispatchableHandle[HtBuffer]
  Semaphore* = NonDispatchableHandle[HtSemaphore]
  ShaderModule* = NonDispatchableHandle[HtShaderModule]
  SamplerYcbcrConversionKHR* = SamplerYcbcrConversion
  DisplayModeKHR* = NonDispatchableHandle[HtDisplayModeKHR]
  DescriptorSetLayout* = NonDispatchableHandle[HtDescriptorSetLayout]
  BufferView* = NonDispatchableHandle[HtBufferView]
  DebugUtilsMessengerEXT* = NonDispatchableHandle[HtDebugUtilsMessengerEXT]
  CommandPool* = NonDispatchableHandle[HtCommandPool]
  QueryPool* = NonDispatchableHandle[HtQueryPool]
  Image* = NonDispatchableHandle[HtImage]
  DeviceMemory* = NonDispatchableHandle[HtDeviceMemory]
  Framebuffer* = NonDispatchableHandle[HtFramebuffer]
  PerformanceConfigurationINTEL* = NonDispatchableHandle[HtPerformanceConfigurationINTEL]
  IndirectCommandsLayoutNV* = NonDispatchableHandle[HtIndirectCommandsLayoutNV]
  DeferredOperationKHR* = NonDispatchableHandle[HtDeferredOperationKHR]
  Queue* = Handle[HtQueue]
  Sampler* = NonDispatchableHandle[HtSampler]
  RenderPass* = NonDispatchableHandle[HtRenderPass]
  ImageView* = NonDispatchableHandle[HtImageView]
  PrivateDataSlotEXT* = NonDispatchableHandle[HtPrivateDataSlotEXT]
  SamplerYcbcrConversion* = NonDispatchableHandle[HtSamplerYcbcrConversion]
  Instance* = Handle[HtInstance]
  DescriptorUpdateTemplate* = NonDispatchableHandle[HtDescriptorUpdateTemplate]
  PhysicalDevice* = Handle[HtPhysicalDevice]
  CommandBuffer* = Handle[HtCommandBuffer]
  Pipeline* = NonDispatchableHandle[HtPipeline]
  DescriptorSet* = NonDispatchableHandle[HtDescriptorSet]
  Event* = NonDispatchableHandle[HtEvent]
  ValidationCacheEXT* = NonDispatchableHandle[HtValidationCacheEXT]
  AccelerationStructureNV* = AccelerationStructureKHR
  Fence* = NonDispatchableHandle[HtFence]
  DescriptorUpdateTemplateKHR* = DescriptorUpdateTemplate